steps:
- name: gradle:5.6.2-jdk8
  entrypoint: gradle
  args: ['build', 'jacocoTestReport']
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'cp', '-r', 'build/reports', 'gs://13980-build-artifacts/$BUILD_ID']
